---
version: "2.2"

services:
  pwnql:
    build: PwnQL_1/
    restart: always
    ports:
      - "8080:80"
    environment:
      - PWNQL_1_FLAG=${PWNQL_1_FLAG}
      - MYSQL_USER=${MYSQLI_USER}
      - MYSQL_PASSWORD=${MYSQLI_PASSWORD}
      - MYSQL_DATABASE=${MYSQLI_DATABASE}
    depends_on:
      - mysqli

  mysqli:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - 3306
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=${MYSQLI_USER}
      - MYSQL_PASSWORD=${MYSQLI_PASSWORD}
      - MYSQL_DATABASE=${MYSQLI_DATABASE}
    volumes:
      - "./MySQLi/:/docker-entrypoint-initdb.d/"
    
  ssrf:
    build: 0xSSRF/
    restart: always
    ports:
      - "3000:3000"
    environment:
      - FLAG_SSRF=${FLAG_SSRF}

  youshoulddie:
    build: YouShouldDie/
    restart: always
    ports:
      - "9000:80"
    environment:
      - FLAG_MARK3TING=${FLAG_MARK3TING}

  winventorybdd:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - 3306
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=${SQL_USER}
      - MYSQL_PASSWORD=${SQL_PASSWORD}
      - MYSQL_DATABASE=${SQL_DATABASE}
    volumes:
      - "./winventorybdd/:/docker-entrypoint-initdb.d/"

  winventory:
    build: Winventory/
    restart: always
    ports:
      - "8050:80"
    environment:
      - MYSQL_USER=${SQL_USER}
      - MYSQL_PASSWORD=${SQL_PASSWORD}
      - MYSQL_DATABASE=${SQL_DATABASE}
    depends_on:
      - winventorybdd

  blackmarket:
    build: Black_Market/
    restart: always
    mem_limit: 1512m
    ports:
      - "3050:3000"